name: shell commands

on:
  - push

jobs:
  run-shell-commands:
  steps:
    - name: echo string
      run: echo "Hello"
    - name: Multi line string
      run: |
        pwd
        node -v
        ls -a